---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: heading
  label: Data
- type: document
  path: exampleSite/data/homepage.yml
  label: Homepage
- type: document
  path: exampleSite/data/marketplace.yml
  label: Marketplace
- type: document
  path: exampleSite/data/technology.yml
  label: Technology
- type: document
  path: exampleSite/data/pricing.yml
  label: Pricing
- type: heading
  label: Marketplace Pages
- type: document
  path: exampleSite/data/winespirits.yml
  label: Wine-Spirits
- type: document
  path: exampleSite/data/collectiblesother.yml
  label: Collectibles-Other
- type: document
  path: exampleSite/data/finediamonds.yml
  label: Find-Diamonds
- type: document
  path: exampleSite/data/firearmsammo.yml
  label: Firearms-Ammo
- type: document
  path: exampleSite/data/medicalbio.yml
  label: Medical-Bio
- type: document
  path: exampleSite/data/preciousmetals.yml
  label: Precious-Metals
- type: heading
  label: Content
- type: document
  path: exampleSite/content/contact/_index.md
  label: Contact
- type: document
  path: exampleSite/content/marketplaces/_index.md
  label: Marketplaces
- type: document
  path: exampleSite/content/pricing/_index.md
  label: Pricing
- type: document
  path: exampleSite/content/technology/_index.md
  label: Technology
- type: heading
  label: Other
- type: document
  path: exampleSite/content/privacy-policy/_index.md
  label: Privacy Policy
- type: document
  path: exampleSite/content/terms-conditions/_index.md
  label: Terms & Conditions
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content
  label: All Pages
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config.toml
  label: Configuration
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
